# Generated by Django 2.1.3 on 2018-11-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_art',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
