# Generated by Django 2.1.3 on 2018-12-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_news_news_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
