# Generated by Django 2.0.4 on 2018-12-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20181203_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_art',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
